pipeline {
    agent any
    stages {
        stage('Checkout helm chart') {
            steps {
                // Clone the Helm chart repository
                checkout scm
            }
        }
        stage('Deploy') {
            steps {
                script {
                        jobName = sh(returnStdout: true, script: "echo $JOB_NAME").split('/')[-1].trim().toLowerCase()
                        sh "helm upgrade --install $jobName ${currentWs}/kubernetes/helm_charts/core/$jobName --namespace $vabots_namespace --kubeconfig $kubeconfig_path"
                }
            }
        }
    }

}

